import React from 'react';
import { NavLink } from 'react-router-dom';
import style from './index.module.scss';
import ListMenu from './menu';
import scrollProgressBar from '../../helpers/scrollProgressBar'

const ListPage: React.FC = () => {
  const goToAnime = (id: string): void => {
    alert(id);
  };

  const listElements = () => {
    const list = [
      {
        id: '60254fb2f578d98d81f766f3',
        title: 'Mushishi Zoku Shou: Suzu no Shizuku',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/9/72689.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255087f578d98d81f76761',
        title: 'Katanagatari',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/2/50023.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255073f578d98d81f76756',
        title: 'Hotarubi no Mori e',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/8/38229.jpg',
        userStatus: 'planned',
      },
      {
        id: '602553e8f578d98d81f76939',
        title: 'Zoku Sayonara Zetsubou Sensei',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/13/75517.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025503af578d98d81f76738',
        title: 'Usagi Drop',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '11',
        image: 'https://cdn.myanimelist.net/images/anime/2/29665.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025592df578d98d81f76c31',
        title: 'Kumo no Mukou, Yakusoku no Basho',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/1/433.jpg',
        userStatus: 'planned',
      },
      {
        id: '602551f5f578d98d81f76825',
        title: 'Detroit Metal City',
        score: '- ',
        type: 'OVA',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/3/9853.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025554df578d98d81f769fd',
        title: 'Mind Game',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/1722/96276.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025504df578d98d81f76742',
        title: 'Mononoke',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/3/20713.jpg',
        userStatus: 'planned',
      },
      {
        id: '602554edf578d98d81f769c6',
        title: 'Saraiya Goyou',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/4/75203.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254f6bf578d98d81f766d0',
        title: 'Monster',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '74',
        image: 'https://cdn.myanimelist.net/images/anime/10/18793.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254f64f578d98d81f766cd',
        title: 'Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-hen',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/10/82947.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255bb3f578d98d81f76d9a',
        title: 'Yoake Tsugeru Lu no Uta',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/5/84260.jpg',
        userStatus: 'planned',
      },
      {
        id: '602555f7f578d98d81f76a5c',
        title: 'Aoi Bungaku Series',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/10/17471.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255015f578d98d81f76724',
        title: 'Perfect Blue',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/11/79127.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255293f578d98d81f7687e',
        title: 'Paprika',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/1929/93629.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025510ef578d98d81f767ac',
        title: 'Sennen Joyuu',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/1648/93626.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025517ef578d98d81f767ea',
        title: 'Death Parade',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/5/71553.jpg',
        userStatus: 'planned',
      },
      {
        id: '602550f4f578d98d81f7679c',
        title: 'Tokyo Godfathers',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/1144/93627.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255d96f578d98d81f76eb1',
        title: 'Ristorante Paradiso',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '11',
        image: 'https://cdn.myanimelist.net/images/anime/13/17488.jpg',
        userStatus: 'planned',
      },
      {
        id: '602553f3f578d98d81f7693f',
        title: 'Ergo Proxy',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '23',
        image: 'https://cdn.myanimelist.net/images/anime/11/6259.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255544f578d98d81f769f8',
        title: 'Hadashi no Gen',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/12/10128.jpg',
        userStatus: 'planned',
      },
      {
        id: '602556a2f578d98d81f76abf',
        title: 'Giovanni no Shima',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/5/56297.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254f5bf578d98d81f766c8',
        title: 'Mob Psycho 100 II',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1918/96303.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255acef578d98d81f76d1a',
        title: 'Gallery Fake',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '37',
        image: 'https://cdn.myanimelist.net/images/anime/10/30129.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025561af578d98d81f76a70',
        title: 'Memories',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '3',
        image: 'https://cdn.myanimelist.net/images/anime/9/74781.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025543cf578d98d81f76963',
        title: 'Top wo Nerae! Gunbuster',
        score: '- ',
        type: 'OVA',
        progress: 0,
        episodes: '6',
        image: 'https://cdn.myanimelist.net/images/anime/1303/92309.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254fb4f578d98d81f766f4',
        title: 'JoJo no Kimyou na Bouken Part 5: Ougon no Kaze',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '39',
        image: 'https://cdn.myanimelist.net/images/anime/1572/95010.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025524cf578d98d81f76858',
        title: 'Dennou Coil',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '26',
        image: 'https://cdn.myanimelist.net/images/anime/5/12844.jpg',
        userStatus: 'planned',
      },
      {
        id: '602556def578d98d81f76ade',
        title: 'Tenshi no Tamago',
        score: '- ',
        type: 'OVA',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/11/63181.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255278f578d98d81f76871',
        title: 'Boku no Hero Academia 4th Season',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '25',
        image: 'https://cdn.myanimelist.net/images/anime/1412/107914.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255940f578d98d81f76c3b',
        title: 'Irozuku Sekai no Ashita kara',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1424/93855.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255692f578d98d81f76ab7',
        title: 'Aggressive Retsuko (ONA)',
        score: '- ',
        type: 'ONA',
        progress: 0,
        episodes: '10',
        image: 'https://cdn.myanimelist.net/images/anime/12/89288.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254feff578d98d81f76711',
        title: 'Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1444/108005.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255079f578d98d81f76759',
        title: 'Mushoku Tensei: Isekai Ittara Honki Dasu',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '11',
        image: 'https://cdn.myanimelist.net/images/anime/1068/111129.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255a95f578d98d81f76cfc',
        title: 'Shigofumi',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/4/50787.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255528f578d98d81f769eb',
        title: 'Aggressive Retsuko (ONA) 2nd Season',
        score: '- ',
        type: 'ONA',
        progress: 0,
        episodes: '10',
        image: 'https://cdn.myanimelist.net/images/anime/1739/101117.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025579df578d98d81f76b49',
        title: 'Aggressive Retsuko',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '100',
        image: 'https://cdn.myanimelist.net/images/anime/2/84193.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025500af578d98d81f7671e',
        title: 'Mo Dao Zu Shi',
        score: '- ',
        type: 'ONA',
        progress: 0,
        episodes: '15',
        image: 'https://cdn.myanimelist.net/images/anime/1253/93893.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254f93f578d98d81f766e5',
        title: 'Yuru Camp△ Season 2',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1255/110636.jpg',
        userStatus: 'planned',
      },
      {
        id: '602561dbf578d98d81f77137',
        title: 'Fuujin Monogatari',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/4/50349.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255337f578d98d81f768d8',
        title: 'Haibane Renmei',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/9/13134.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255fcaf578d98d81f77000',
        title: 'Mahoutsukai ni Taisetsu na Koto: Natsu no Sora',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/10/50399.jpg',
        userStatus: 'planned',
      },
      {
        id: '602556b1f578d98d81f76ac6',
        title: 'Aria the Animation',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/2/77620.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255a7af578d98d81f76cea',
        title: 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1523/108380.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025596ef578d98d81f76c52',
        title: 'Psycho-Pass 3',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '8',
        image: 'https://cdn.myanimelist.net/images/anime/1406/104344.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254fd2f578d98d81f76702',
        title: 'Haikyuu!!: To the Top 2nd Season',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1453/106768.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255b81f578d98d81f76d7d',
        title: 'Josee to Tora to Sakana-tachi',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/1714/108892.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255e24f578d98d81f76f03',
        title: 'Shokugeki no Souma: Gou no Sara',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1756/108000.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025642ef578d98d81f77299',
        title: 'Kuma Kuma Kuma Bear',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1413/110712.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255579f578d98d81f76a14',
        title: 'Jibaku Shounen Hanako-kun',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1700/104788.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025506cf578d98d81f76752',
        title: 'Haikyuu!!: To the Top',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1813/105367.jpg',
        userStatus: 'planned',
      },
      {
        id: '602552fdf578d98d81f768b7',
        title: 'Kakushigoto (TV)',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1476/106372.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025502ef578d98d81f76732',
        title: 'Banana Fish',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '24',
        image: 'https://cdn.myanimelist.net/images/anime/1190/93472.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255e05f578d98d81f76eef',
        title: 'Log Horizon: Entaku Houkai',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1510/108026.jpg',
        userStatus: 'planned',
      },
      {
        id: '602558ddf578d98d81f76c02',
        title: 'Fugou Keiji: Balance:Unlimited',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '11',
        image: 'https://cdn.myanimelist.net/images/anime/1066/106556.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255448f578d98d81f7696a',
        title: 'Uchouten Kazoku',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/3/85433.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025509ef578d98d81f7676c',
        title: 'Luo Xiao Hei Zhan Ji (Movie)',
        score: '- ',
        type: 'Movie',
        progress: 0,
        episodes: '1',
        image: 'https://cdn.myanimelist.net/images/anime/1583/108598.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255d46f578d98d81f76e83',
        title: 'Isekai Quartet 2',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1030/103383.jpg',
        userStatus: 'planned',
      },
      {
        id: '602555aef578d98d81f76a30',
        title: 'Ranma ½',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '161',
        image: 'https://cdn.myanimelist.net/images/anime/13/6441.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255f16f578d98d81f76f94',
        title: 'Mnemosyne: Mnemosyne no Musume-tachi',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '6',
        image: 'https://cdn.myanimelist.net/images/anime/10/10918.jpg',
        userStatus: 'planned',
      },
      {
        id: '602555f9f578d98d81f76a5d',
        title: 'Black Jack',
        score: '- ',
        type: 'OVA',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/5/12978.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255721f578d98d81f76b00',
        title: 'Kami no Tou',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1702/106229.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255a8df578d98d81f76cf7',
        title:
          'Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta...',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1483/107061.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255405f578d98d81f76948',
        title: 'Id:Invaded',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1889/105337.jpg',
        userStatus: 'planned',
      },
      {
        id: '60256490f578d98d81f772d3',
        title: 'Reikenzan: Hoshikuzu-tachi no Utage',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/11/78196.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025645bf578d98d81f772b3',
        title: "Knight's & Magic",
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1472/93813.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254f8cf578d98d81f766e1',
        title: 'Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1132/110666.jpg',
        userStatus: 'planned',
      },
      {
        id: '602551aff578d98d81f76805',
        title:
          'Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen 2nd Season',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1464/107998.jpg',
        userStatus: 'planned',
      },
      {
        id: '602552d6f578d98d81f7689f',
        title:
          'Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '14',
        image: 'https://cdn.myanimelist.net/images/anime/1582/101697.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255955f578d98d81f76c46',
        title:
          'Shinchou Yuusha: Kono Yuusha ga Ore Tueee Kuse ni Shinchou Sugiru',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1715/103419.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255c16f578d98d81f76dd3',
        title: 'Sword Art Online: Alicization - War of Underworld 2nd Season',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '11',
        image: 'https://cdn.myanimelist.net/images/anime/1438/105106.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255605f578d98d81f76a64',
        title: 'Kami nomi zo Shiru Sekai',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/2/43361.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255d81f578d98d81f76ea6',
        title: 'Slayers Special',
        score: '- ',
        type: 'OVA',
        progress: 0,
        episodes: '3',
        image: 'https://cdn.myanimelist.net/images/anime/1372/92532.jpg',
        userStatus: 'planned',
      },
      {
        id: '602555b3f578d98d81f76a33',
        title: 'Slayers',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '26',
        image: 'https://cdn.myanimelist.net/images/anime/6/19870.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255019f578d98d81f76726',
        title: 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1958/107912.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025534df578d98d81f768e4',
        title: 'Gochuumon wa Usagi Desu ka? Bloom',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1900/109179.jpg',
        userStatus: 'planned',
      },
      {
        id: '602555cef578d98d81f76a45',
        title: 'Akudama Drive',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1468/109172.jpg',
        userStatus: 'planned',
      },
      {
        id: '60254ff6f578d98d81f76715',
        title: 'Jujutsu Kaisen (TV)',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '24',
        image: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg',
        userStatus: 'planned',
      },
      {
        id: '602552dcf578d98d81f768a3',
        title: 'Maoujou de Oyasumi',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1448/108514.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025536bf578d98d81f768f5',
        title: 'Yuukoku no Moriarty',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '11',
        image: 'https://cdn.myanimelist.net/images/anime/1464/108330.jpg',
        userStatus: 'planned',
      },
      {
        id: '60255ea2f578d98d81f76f54',
        title: 'Munou na Nana',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/1301/110433.jpg',
        userStatus: 'planned',
      },
      {
        id: '6025510df578d98d81f767ab',
        title: 'Ookami to Koushinryou',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '13',
        image: 'https://cdn.myanimelist.net/images/anime/5/59401.jpg',
        userStatus: 'planned',
      },
      {
        id: '602550f6f578d98d81f7679d',
        title: 'Wonder Egg Priority',
        score: '- ',
        type: 'TV series',
        progress: 0,
        episodes: '12',
        image: 'https://cdn.myanimelist.net/images/anime/1079/110751.jpg',
        userStatus: 'planned',
      },
    ];
    return list.map((element, index) => (
      <NavLink
        key={element.id}
        to={'/anime/' + element.id}
        onClick={() => {
          goToAnime(element.id);
        }}
      >
        <div className={style.elementWrapper} key={index}>
          <div>
            <div className={`${style.verticalAlign} ${style.firstColumn}`}>
              {index + 1}
            </div>
          </div>
          <div>
            <img src={element.image} alt="poster" />
          </div>
          <div>
            <div className={`${style.verticalAlign} ${style.titleColumn}`}>
              {element.title}
            </div>
          </div>
          <div>
            <div className={`${style.verticalAlign} ${style.fourthColumn}`}>
              {element.score} /10
            </div>
          </div>
          <div>
            <div className={`${style.verticalAlign} ${style.fivesColumn}`}>
              {element.type}
            </div>
          </div>
          <div>
            <div className={`${style.verticalAlign} ${style.sixColumn}`}>
              {element.progress}/{element.episodes}
            </div>
          </div>
        </div>
      </NavLink>
    ));
  };
  

  const progressBar = () => {
    const progress = document.getElementsByClassName(style.scrollbar) as HTMLCollectionOf<HTMLElement>;
    const scrollElement = document.getElementsByClassName(style.scrollableContent) as HTMLCollectionOf<HTMLElement>;
    scrollProgressBar(progress[0], scrollElement[0])
  };

  return (
    <div className={style.wrapper}>
      <div>
        <div className={style.scrollbar} />
        <div className={style.content}>
          <div className={style.tableLabels}>
            <div>#</div>
            <div>Image</div>
            <div className={style.tableLabelName}>Name</div>
            <div>Score</div>
            <div>Type</div>
            <div>Progress</div>
          </div>
          <div className={style.spacerLine} />
          <div className={style.scrollableContent} onScroll={progressBar}>
            {listElements()}
          </div>
        </div>
      </div>
      <div className={style.menu}>
        <ListMenu />
      </div>
    </div>
  );
};


export default ListPage;
